import uuid
from datetime import datetime
from typing import Optional
from sqlalchemy import String, Text, Float, Integer, DateTime, ForeignKey, Index, CheckConstraint
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from geoalchemy2 import Geography
from app.models.base_model import UUIDBaseModel


class RiskEvent(UUIDBaseModel):
    """
    Unified real-time risk events (crime, harassment, lighting_problem, protests, disruptions).
    """
    __tablename__ = "risk_events"

    event_type: Mapped[str] = mapped_column(String(100), nullable=False, index=True) # crime, harassment, lighting_problem, protest, etc.
    source_type: Mapped[str] = mapped_column(String(50), nullable=False, index=True) # news, government, community, police
    source_reference: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    location = mapped_column(Geography(geometry_type="POINT", srid=4326), nullable=False)
    severity: Mapped[float] = mapped_column(Float, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, default=1.0, nullable=False)
    verification_status: Mapped[str] = mapped_column(String(50), default="UNVERIFIED", nullable=False, index=True)
    valid_from: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    valid_until: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True, index=True)

    __table_args__ = (
        CheckConstraint("severity >= 0.0 AND severity <= 1.0", name="check_valid_risk_event_severity"),
        CheckConstraint("confidence >= 0.0 AND confidence <= 1.0", name="check_valid_risk_event_confidence"),
        CheckConstraint("valid_until IS NULL OR valid_until >= valid_from", name="check_valid_risk_event_dates"),
        Index("idx_risk_events_location", "location", postgresql_using="gist"),
    )


class ModelVersion(UUIDBaseModel):
    """
    Machine Learning model registry tracking versions, features, metrics, and artifact URIs.
    """
    __tablename__ = "model_versions"

    model_name: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    version: Mapped[str] = mapped_column(String(50), nullable=False, unique=True, index=True)
    algorithm: Mapped[str] = mapped_column(String(100), nullable=False)
    training_started_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    training_completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    training_data_start: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    training_data_end: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    feature_list: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    metrics: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    artifact_uri: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(50), default="INACTIVE", nullable=False, index=True) # ACTIVE, INACTIVE, DEPRECATED

    # Relationships
    predictions: Mapped[list["RiskPrediction"]] = relationship("RiskPrediction", back_populates="model_version")


class RiskPrediction(UUIDBaseModel):
    """
    Final dynamic risk predictions associated with road segments generated by ML models.
    """
    __tablename__ = "risk_predictions"

    road_segment_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("road_segments.id", ondelete="CASCADE"), nullable=False, index=True)
    prediction_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    time_of_day: Mapped[int] = mapped_column(Integer, nullable=False) # 0 to 23
    day_of_week: Mapped[int] = mapped_column(Integer, nullable=False) # 0 to 6
    risk_score: Mapped[float] = mapped_column(Float, nullable=False)   # 0.0 to 1.0
    confidence: Mapped[float] = mapped_column(Float, nullable=False)   # 0.0 to 1.0
    risk_level: Mapped[str] = mapped_column(String(20), nullable=False, index=True) # LOW, MODERATE, HIGH, UNKNOWN
    model_version_id: Mapped[Optional[uuid.UUID]] = mapped_column(UUID(as_uuid=True), ForeignKey("model_versions.id", ondelete="SET NULL"), nullable=True, index=True)
    data_freshness: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    feature_snapshot: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)

    # Relationships
    model_version: Mapped[Optional["ModelVersion"]] = relationship("ModelVersion", back_populates="predictions")

    __table_args__ = (
        CheckConstraint("risk_score >= 0.0 AND risk_score <= 1.0", name="check_valid_risk_score"),
        CheckConstraint("confidence >= 0.0 AND confidence <= 1.0", name="check_valid_risk_confidence"),
        CheckConstraint("time_of_day >= 0 AND time_of_day <= 23", name="check_valid_time_of_day"),
        CheckConstraint("day_of_week >= 0 AND day_of_week <= 6", name="check_valid_day_of_week"),
    )


class ModelPrediction(UUIDBaseModel):
    """
    Raw machine learning model predictions recorded before fusion or safety cost adjustment.
    """
    __tablename__ = "model_predictions"

    model_version_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("model_versions.id", ondelete="CASCADE"), nullable=False, index=True)
    road_segment_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("road_segments.id", ondelete="CASCADE"), nullable=False, index=True)
    prediction_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    prediction: Mapped[float] = mapped_column(Float, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    features: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
